services:
  # PostgreSQL Database
  - type: pserv
    name: personal-website-db
    env: docker
    plan: free
    region: oregon
    databaseName: personal_website
    databaseUser: personal_website_user
    ipAllowList: []

  # Web Service
  - type: web
    name: personal-website
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: personal-website-db
          property: connectionString
    healthCheckPath: /
